"""fix User

Revision ID: dc94f7460a48
Revises: 46ffd7593894
Create Date: 2024-03-11 20:23:39.821159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc94f7460a48'
down_revision = '46ffd7593894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('year_of_admission',
               existing_type=mysql.YEAR(),
               nullable=True)
        batch_op.alter_column('form_of_education_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('group_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('group_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('form_of_education_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('year_of_admission',
               existing_type=mysql.YEAR(),
               nullable=False)

    # ### end Alembic commands ###
